"""
email_sender.py
---------------
SMTP email sending helper for the ANPR Traffic Violation System.

Purpose:
This module sends automated violation notification emails to vehicle owners.

Security:
Email credentials are loaded from the `.env` file instead of being hardcoded
to ensure safe handling of sensitive information.
"""

# Load environment variables from .env file
from dotenv import load_dotenv

import os
import smtplib
from email.message import EmailMessage

# Initialize environment variables
load_dotenv()


def send_email_smtp(to_email: str, subject: str, body: str) -> dict:
    """
    Sends an email using SMTP.

    Parameters
    ----------
    to_email : str
        Recipient email address (vehicle owner).

    subject : str
        Email subject line.

    body : str
        Email message content (generated by Gemini / fallback template).

    Returns
    -------
    dict
        {
            "sent": True/False,
            "error": error_message_if_any
        }
    """

    # ------------------------------------------------------------
    # Load SMTP configuration from environment variables
    # ------------------------------------------------------------
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")   # Gmail SMTP server
    smtp_port = int(os.getenv("SMTP_PORT", "587"))         # TLS port
    smtp_user = os.getenv("SMTP_USER", "").strip()         # sender email
    smtp_pass = os.getenv("SMTP_PASS", "").strip()         # app password

    # If credentials are missing, return error safely
    if not smtp_user or not smtp_pass:
        return {"sent": False, "error": "SMTP credentials missing (check .env)"}

    try:
        # ------------------------------------------------------------
        # Construct email message
        # ------------------------------------------------------------
        msg = EmailMessage()

        msg["From"] = smtp_user      # sender email
        msg["To"] = to_email         # recipient email
        msg["Subject"] = subject     # subject line

        # Email body text
        msg.set_content(body)

        # ------------------------------------------------------------
        # Connect to SMTP server and send email
        # ------------------------------------------------------------
        with smtplib.SMTP(smtp_host, smtp_port) as server:

            # Identify server
            server.ehlo()

            # Start encrypted TLS session
            server.starttls()

            # Login using SMTP credentials
            server.login(smtp_user, smtp_pass)

            # Send the email message
            server.send_message(msg)

        # If successful
        return {"sent": True}

    except Exception as e:
        # Catch any SMTP / network errors
        return {"sent": False, "error": str(e)}